### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by spddl** [amitxvv/EVA#4]
https://github.com/amitxvv/EVA/blob/main/src/1803/EXPLORE%20MOUNT%20DIRECTORY/Windows/Modules/EVA.reg#L35

These environment variables are used by a lot of programs so you override everything else.

Better would be to add the EVA folder with setx https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setx

**Comment by spddl** [comment]
ok you do that in the "POST INSTALL" but the post install script runs every start?

https://github.com/amitxvv/EVA/blob/c55d783865b65b23d450558f667ceada9465aecc/src/1803/EXPLORE%20MOUNT%20DIRECTORY/Windows/Modules/EVA.reg#L29

wouldn't RunOnce be better?

**Comment by amitxvv** [comment]
I already use setx and refresh the environment variables at the beginning of the script, i will remove it from integrating it into the registry hive preinstall.

No, if the user enters breakpoint the script must auto-start again so i would need to add the script to RunOnce each time anyway.
